# Generated by Django 5.2.1 on 2025-05-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd',
            name='date_emprunt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='date_emprunt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='date_emprunt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
