# Generated by Django 5.2.1 on 2025-05-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0002_alter_cd_date_emprunt_alter_dvd_date_emprunt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cd',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='dvd',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='livre',
            old_name='name',
            new_name='nom',
        ),
    ]
