# Generated by Django 5.2.1 on 2025-05-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0005_emprunt'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='date_retour_effectif',
            field=models.DateField(blank=True, null=True),
        ),
    ]
